CREATE TYPE STATUS AS ENUM ('PENDING','APPROVED', 'DECLINED');

CREATE TABLE DOCUMENTS (
  CREATED_AT TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP,
  DELETED_AT TIMESTAMP,
  NAME VARCHAR(256) NOT NULL,
  DESCRIPTION VARCHAR(256) NOT NULL,
  VERSION VARCHAR(256) NOT NULL,
  AUTHOR VARCHAR(256) NOT NULL,
  STATUS STATUS NOT NULL,
  UNIQUE (NAME, VERSION),
  PRIMARY KEY (NAME, VERSION)
);

CREATE TABLE SNIPPETS (
  ID   SERIAL PRIMARY KEY,
  CREATED_AT TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP,
  DELETED_AT TIMESTAMP,
  TEXT VARCHAR(256) NOT NULL,
  TEST_CASE VARCHAR(256),
  DOCUMENT_NAME VARCHAR(256),
  DOCUMENT_VERSION VARCHAR(256),

  UNIQUE (DOCUMENT_NAME, DOCUMENT_VERSION),
  FOREIGN KEY (DOCUMENT_NAME, DOCUMENT_VERSION) REFERENCES DOCUMENTS(NAME, VERSION) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE DOCUMENT_DEPENDENCIES (
  DOCUMENT_NAME  VARCHAR(256),
  DOCUMENT_VERSION VARCHAR(256),
  DEPENDENCY_NAME  VARCHAR(256),
  DEPENDENCY_VERSION VARCHAR(256),
  UNIQUE (DOCUMENT_NAME , DOCUMENT_VERSION, DEPENDENCY_NAME, DEPENDENCY_VERSION),
  FOREIGN KEY (DOCUMENT_NAME, DOCUMENT_VERSION) REFERENCES DOCUMENTS(NAME, VERSION) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (DEPENDENCY_NAME, DEPENDENCY_VERSION)  REFERENCES DOCUMENTS(NAME, VERSION) ON DELETE CASCADE ON UPDATE CASCADE
);