// Code generated by protoc-gen-go. DO NOT EDIT.
// source: document.proto

/*
Package registry is a generated protocol buffer package.

It is generated from these files:
	document.proto
	registry.proto

It has these top-level messages:
	Document
	Snippet
	GetDocumentsRequest
	GetDocumentsResponse
	GetDocumentRequest
	GetDocumentResponse
	CreateDocumentRequest
	CreateDocumentResponse
	ApprovedDocumentRequest
	ApprovedDocumentResponse
	DeclinedDocumentRequest
	DeclinedDocumentResponse
	PendingDocumentRequest
	PendingDocumentResponse
*/
package registry

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status int32

const (
	Status_PENDING  Status = 0
	Status_APPROVED Status = 1
	Status_DECLINED Status = 2
)

var Status_name = map[int32]string{
	0: "PENDING",
	1: "APPROVED",
	2: "DECLINED",
}
var Status_value = map[string]int32{
	"PENDING":  0,
	"APPROVED": 1,
	"DECLINED": 2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Document struct {
	Id           int64                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name         string                     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description  string                     `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Version      string                     `protobuf:"bytes,4,opt,name=version" json:"version,omitempty"`
	CreatedAt    *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt    *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	Author       string                     `protobuf:"bytes,7,opt,name=author" json:"author,omitempty"`
	Status       Status                     `protobuf:"varint,8,opt,name=status,enum=registry.Status" json:"status,omitempty"`
	Dependencies []*Document                `protobuf:"bytes,9,rep,name=dependencies" json:"dependencies,omitempty"`
	Snippet      *Snippet                   `protobuf:"bytes,10,opt,name=snippet" json:"snippet,omitempty"`
}

func (m *Document) Reset()                    { *m = Document{} }
func (m *Document) String() string            { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()               {}
func (*Document) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Document) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Document) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Document) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Document) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Document) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Document) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Document) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Document) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_PENDING
}

func (m *Document) GetDependencies() []*Document {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

func (m *Document) GetSnippet() *Snippet {
	if m != nil {
		return m.Snippet
	}
	return nil
}

type Snippet struct {
	Text     string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	TestCase string `protobuf:"bytes,2,opt,name=test_case,json=testCase" json:"test_case,omitempty"`
}

func (m *Snippet) Reset()                    { *m = Snippet{} }
func (m *Snippet) String() string            { return proto.CompactTextString(m) }
func (*Snippet) ProtoMessage()               {}
func (*Snippet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Snippet) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Snippet) GetTestCase() string {
	if m != nil {
		return m.TestCase
	}
	return ""
}

func init() {
	proto.RegisterType((*Document)(nil), "registry.Document")
	proto.RegisterType((*Snippet)(nil), "registry.Snippet")
	proto.RegisterEnum("registry.Status", Status_name, Status_value)
}

func init() { proto.RegisterFile("document.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0xcb, 0x8a, 0xd4, 0x40,
	0x14, 0x35, 0xc9, 0x98, 0xc7, 0xcd, 0xd0, 0xc4, 0x5a, 0x48, 0x31, 0x2e, 0x0c, 0xb3, 0x0a, 0x0a,
	0x19, 0x6c, 0x41, 0xd0, 0x5d, 0x33, 0x09, 0x32, 0x20, 0x6d, 0x53, 0x8a, 0xdb, 0xa6, 0x3a, 0x75,
	0x6d, 0x0b, 0xcc, 0x83, 0xd4, 0x8d, 0xe8, 0x17, 0xf8, 0xdb, 0x92, 0x4a, 0x0a, 0xdb, 0x95, 0xbb,
	0x3a, 0x2f, 0xea, 0x70, 0x2e, 0x6c, 0x54, 0xdf, 0x4c, 0x2d, 0x76, 0x54, 0x0e, 0x63, 0x4f, 0x3d,
	0x8b, 0x47, 0x3c, 0x6b, 0x43, 0xe3, 0xaf, 0x9b, 0xe7, 0xe7, 0xbe, 0x3f, 0x7f, 0xc7, 0x3b, 0xcb,
	0x9f, 0xa6, 0xaf, 0x77, 0xa4, 0x5b, 0x34, 0x24, 0xdb, 0x61, 0xb1, 0xde, 0xfe, 0x0e, 0x20, 0xae,
	0xd6, 0x34, 0xdb, 0x80, 0xaf, 0x15, 0xf7, 0x72, 0xaf, 0x08, 0x84, 0xaf, 0x15, 0x63, 0x70, 0xd5,
	0xc9, 0x16, 0xb9, 0x9f, 0x7b, 0x45, 0x22, 0xec, 0x9b, 0xe5, 0x90, 0x2a, 0x34, 0xcd, 0xa8, 0x07,
	0xd2, 0x7d, 0xc7, 0x03, 0x2b, 0x5d, 0x52, 0x8c, 0x43, 0xf4, 0x03, 0x47, 0x33, 0xab, 0x57, 0x56,
	0x75, 0x90, 0xbd, 0x05, 0x68, 0x46, 0x94, 0x84, 0xea, 0x28, 0x89, 0x3f, 0xce, 0xbd, 0x22, 0xdd,
	0xde, 0x94, 0x4b, 0xc5, 0xd2, 0x55, 0x2c, 0x3f, 0xbb, 0x8a, 0x22, 0x59, 0xdd, 0x3b, 0x9a, 0xa3,
	0xd3, 0xa0, 0x5c, 0x34, 0xfc, 0x7f, 0x74, 0x75, 0xef, 0x88, 0x3d, 0x85, 0x50, 0x4e, 0xf4, 0xad,
	0x1f, 0x79, 0x64, 0xeb, 0xac, 0x88, 0x15, 0x10, 0x1a, 0x92, 0x34, 0x19, 0x1e, 0xe7, 0x5e, 0xb1,
	0xd9, 0x66, 0xa5, 0x9b, 0xad, 0xfc, 0x64, 0x79, 0xb1, 0xea, 0xec, 0x0d, 0x5c, 0x2b, 0x1c, 0xb0,
	0x53, 0xd8, 0x35, 0x1a, 0x0d, 0x4f, 0xf2, 0xa0, 0x48, 0xb7, 0xec, 0xaf, 0xdf, 0x2d, 0x28, 0xfe,
	0xf1, 0xb1, 0x97, 0x10, 0x99, 0x4e, 0x0f, 0x03, 0x12, 0x07, 0xdb, 0xf8, 0xc9, 0xc5, 0x17, 0x8b,
	0x20, 0x9c, 0xe3, 0xf6, 0x1d, 0x44, 0x2b, 0x37, 0xef, 0x4e, 0xf8, 0x93, 0xec, 0x25, 0x12, 0x61,
	0xdf, 0xec, 0x19, 0x24, 0x84, 0x86, 0x8e, 0x8d, 0x34, 0xee, 0x20, 0xf1, 0x4c, 0xdc, 0x4b, 0x83,
	0x2f, 0x5e, 0x41, 0xb8, 0x54, 0x66, 0x29, 0x44, 0x87, 0x7a, 0x5f, 0x3d, 0xec, 0xdf, 0x67, 0x8f,
	0xd8, 0x35, 0xc4, 0xbb, 0xc3, 0x41, 0x7c, 0xfc, 0x52, 0x57, 0x99, 0x37, 0xa3, 0xaa, 0xbe, 0xff,
	0xf0, 0xb0, 0xaf, 0xab, 0xcc, 0x3f, 0x85, 0x76, 0xb4, 0xd7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x07, 0x42, 0x0c, 0x04, 0x3c, 0x02, 0x00, 0x00,
}
