// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entity.proto

/*
Package registry is a generated protocol buffer package.

It is generated from these files:
	entity.proto
	registry.proto

It has these top-level messages:
	Entity
	Snippet
	GetEntitiesRequest
	GetEntitiesResponse
	GetEntityRequest
	GetEntityResponse
	CreateEntityRequest
	CreateEntityResponse
	ApprovedEntityRequest
	ApprovedEntityResponse
	DeclinedEntityRequest
	DeclinedEntityResponse
	PendingEntityRequest
	PendingEntityResponse
*/
package registry

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status int32

const (
	Status_PENDING  Status = 0
	Status_APPROVED Status = 1
	Status_DECLINED Status = 2
)

var Status_name = map[int32]string{
	0: "PENDING",
	1: "APPROVED",
	2: "DECLINED",
}
var Status_value = map[string]int32{
	"PENDING":  0,
	"APPROVED": 1,
	"DECLINED": 2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Entity struct {
	// @inject_tag: db:"id,omitempty"
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty" db:"id,omitempty"`
	// @inject_tag: db:"name"
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty" db:"name"`
	// @inject_tag: db:"description"
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty" db:"description"`
	// @inject_tag: db:"type"
	Type string `protobuf:"bytes,4,opt,name=type" json:"type,omitempty" db:"type"`
	// @inject_tag: db:"created_at"
	CreatedAt *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt" json:"created_at,omitempty" db:"created_at"`
	// @inject_tag: db:"updated_at"
	UpdatedAt *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty" db:"updated_at"`
	// @inject_tag: db:"author"
	Author string `protobuf:"bytes,7,opt,name=author" json:"author,omitempty" db:"author"`
	// @inject_tag: db:"status"
	Status Status `protobuf:"varint,8,opt,name=status,enum=registry.Status" json:"status,omitempty" db:"status"`
	// @inject_tag: db:"dependencies"
	Dependencies []*Entity `protobuf:"bytes,9,rep,name=dependencies" json:"dependencies,omitempty" db:"dependencies"`
	// @inject_tag: db:"snippet"
	Snippet *Snippet `protobuf:"bytes,10,opt,name=snippet" json:"snippet,omitempty" db:"snippet"`
}

func (m *Entity) Reset()                    { *m = Entity{} }
func (m *Entity) String() string            { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()               {}
func (*Entity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Entity) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Entity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Entity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Entity) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Entity) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Entity) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Entity) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Entity) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_PENDING
}

func (m *Entity) GetDependencies() []*Entity {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

func (m *Entity) GetSnippet() *Snippet {
	if m != nil {
		return m.Snippet
	}
	return nil
}

type Snippet struct {
	// @inject_tag: db:"text"
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty" db:"text"`
	// @inject_tag: db:"test_case"
	TestCase string `protobuf:"bytes,2,opt,name=test_case,json=testCase" json:"test_case,omitempty" db:"test_case"`
}

func (m *Snippet) Reset()                    { *m = Snippet{} }
func (m *Snippet) String() string            { return proto.CompactTextString(m) }
func (*Snippet) ProtoMessage()               {}
func (*Snippet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Snippet) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Snippet) GetTestCase() string {
	if m != nil {
		return m.TestCase
	}
	return ""
}

func init() {
	proto.RegisterType((*Entity)(nil), "registry.Entity")
	proto.RegisterType((*Snippet)(nil), "registry.Snippet")
	proto.RegisterEnum("registry.Status", Status_name, Status_value)
}

func init() { proto.RegisterFile("entity.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4f, 0xab, 0x9b, 0x40,
	0x14, 0xc5, 0xab, 0x49, 0xfd, 0x73, 0x0d, 0xc1, 0xce, 0xa2, 0x0c, 0xe9, 0xa2, 0x92, 0x95, 0xb4,
	0x60, 0x68, 0xda, 0x4d, 0xbb, 0x0b, 0x51, 0x4a, 0xa0, 0xa4, 0xc1, 0x96, 0x6e, 0xc3, 0x44, 0x6f,
	0xf3, 0x06, 0x5e, 0x74, 0x70, 0xae, 0x90, 0x7c, 0xf8, 0x07, 0x0f, 0x47, 0x85, 0xbc, 0xd5, 0xdb,
	0xcd, 0x3d, 0xf7, 0x1c, 0xe6, 0xc7, 0xb9, 0x30, 0xc3, 0x8a, 0x24, 0xdd, 0x12, 0xd5, 0xd4, 0x54,
	0x33, 0xaf, 0xc1, 0xb3, 0xd4, 0xd4, 0xdc, 0x16, 0x1f, 0xcf, 0x75, 0x7d, 0x7e, 0xc4, 0x95, 0xd1,
	0x4f, 0xed, 0xff, 0x15, 0xc9, 0x0b, 0x6a, 0x12, 0x17, 0xd5, 0x5b, 0x97, 0x4f, 0x36, 0x38, 0x99,
	0xc9, 0xb2, 0x39, 0xd8, 0xb2, 0xe4, 0x56, 0x64, 0xc5, 0x93, 0xdc, 0x96, 0x25, 0x63, 0x30, 0xad,
	0xc4, 0x05, 0xb9, 0x1d, 0x59, 0xb1, 0x9f, 0x9b, 0x37, 0x8b, 0x20, 0x28, 0x51, 0x17, 0x8d, 0x54,
	0x24, 0xeb, 0x8a, 0x4f, 0xcc, 0xea, 0x5e, 0xea, 0x52, 0x74, 0x53, 0xc8, 0xa7, 0x7d, 0xaa, 0x7b,
	0xb3, 0xef, 0x00, 0x45, 0x83, 0x82, 0xb0, 0x3c, 0x0a, 0xe2, 0x6f, 0x23, 0x2b, 0x0e, 0xd6, 0x8b,
	0xa4, 0x47, 0x4b, 0x46, 0xb4, 0xe4, 0xef, 0x88, 0x96, 0xfb, 0x83, 0x7b, 0x43, 0x5d, 0xb4, 0x55,
	0xe5, 0x18, 0x75, 0x5e, 0x8f, 0x0e, 0xee, 0x0d, 0xb1, 0xf7, 0xe0, 0x88, 0x96, 0x1e, 0xea, 0x86,
	0xbb, 0x86, 0x65, 0x98, 0x58, 0x0c, 0x8e, 0x26, 0x41, 0xad, 0xe6, 0x5e, 0x64, 0xc5, 0xf3, 0x75,
	0x98, 0x8c, 0x75, 0x25, 0x7f, 0x8c, 0x9e, 0x0f, 0x7b, 0xf6, 0x0d, 0x66, 0x25, 0x2a, 0xac, 0x4a,
	0xac, 0x0a, 0x89, 0x9a, 0xfb, 0xd1, 0x24, 0x0e, 0xee, 0xfd, 0x7d, 0x73, 0xf9, 0x0b, 0x17, 0xfb,
	0x0c, 0xae, 0xae, 0xa4, 0x52, 0x48, 0x1c, 0x0c, 0xef, 0xbb, 0xbb, 0x0f, 0xfa, 0x45, 0x3e, 0x3a,
	0x96, 0x3f, 0xc0, 0x1d, 0x34, 0xd3, 0x1c, 0x5e, 0xc9, 0x5c, 0xa0, 0x6b, 0x0e, 0xaf, 0xc4, 0x3e,
	0x80, 0x4f, 0xa8, 0xe9, 0x58, 0x08, 0x3d, 0x1e, 0xc2, 0xeb, 0x84, 0xad, 0xd0, 0xf8, 0xe9, 0x0b,
	0x38, 0x3d, 0x30, 0x0b, 0xc0, 0x3d, 0x64, 0xfb, 0x74, 0xb7, 0xff, 0x19, 0xbe, 0x61, 0x33, 0xf0,
	0x36, 0x87, 0x43, 0xfe, 0xfb, 0x5f, 0x96, 0x86, 0x56, 0x37, 0xa5, 0xd9, 0xf6, 0xd7, 0x6e, 0x9f,
	0xa5, 0xa1, 0x7d, 0x72, 0x4c, 0x65, 0x5f, 0x9f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x55, 0x26, 0xf5,
	0x49, 0x30, 0x02, 0x00, 0x00,
}
